### ISSUE TITLE
Hanging notes when pressing 2 pads at the same time or playing fast

### ISSUE THREAD

**Issue by Fronkielein** [Miq1/FredBoard#13]
### Version

alpha4d

### What is the issue?

TB works okay when I only press one pad after another. As soon as I press two or press many pads fast, I get hanging notes.  
Also: TB  permanently sends MIDI Data (CC14) even when I don't press any pad (I can see it on my plugin's surface).

Sensitivity set to 80-127, noise floor set to 58. Changing any of these values does not help.

**Comment by Frudah** [comment]
I believe this has been fixed with the new tracking system being modified and tested. Reopen if you’re still experiencing issues.
