### ISSUE TITLE
Install quirk / Key illumination levels / Key consistency 

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#14]
### Version

alpha4d

#### 1. LED remains lit after update and Shutdown
Shutdown via menu screen after install of Alpha4d.333
Current draw present with Bot LHS LED lit.
This is only for power down via menu shutdown after the firmware update, unplug and power up, and it does not repeat on the next shutdown.
![ShutDownPWR](https://github.com/user-attachments/assets/b4633f46-3e0b-4149-a9d0-b39af0204641)
![ShutDownLED](https://github.com/user-attachments/assets/83982eae-cd76-4cb9-b491-c7cfd60ae41b)

#### 2.No_Hi-light
The high brightness does not change from the previous (mid?) setting.
Incremental light levels from the low end but the top two are the same.
https://github.com/user-attachments/assets/68d6743d-6e88-4873-9c1d-c24235ee1e7b

#### 3. No_Consistency
Inconsistent tones has two issues.
1) I can't get a button to repeat or another to replace it while it is sounding, its as though once triggered it holds on until the envelope is finished.
2) The buttons will trigger their LEDs without sounding for light touch, I have tried all the sensitivity ranges for a noise threshold of 21.
For the current firmware it doesn't function as a keyboard were you can just play nots reliably, which makes it not usable for live performances which has been requested elsewhere.
https://github.com/user-attachments/assets/0ebf6778-59ad-4021-8f67-db3088ed0455

**Comment by Frudah** [comment]
Highlights should all be consistent. There are some places I previously set them as a constant, but I believe I have removed all constants and changed to the HighLight variable. I made sure to refresh the led buffer before the shutdown procedure finishes, so you shouldn’t see any more lights stuck on.

the other issues sounds like the note hanging/note tracking issue which has also been resolved for scales/classic.
