### ISSUE TITLE
Manic MIDI Channel 1

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#17]
### Version

alpha4g

### What is the issue?

MIDI channel 1 has continuous data output. On MIDI jack (USB MIDI yet to be tested)
(Previous channel 16 problem now solved) 

Note off codes sent for C -1 and Eb-0 or 1 (digits are overlaid)

This starts immediately on power up and continues while powered up.

MIDI channel 1 sends note info to my Synth and generates an audio output.

https://github.com/user-attachments/assets/3806870a-1985-4d11-ac3a-0abb27f3659e

**Comment by Smelter** [comment]
Also persists on Alpha 5

**Comment by Smelter** [comment]
Also persists on Alpha 5

https://github.com/user-attachments/assets/619431fa-00e6-4820-aaec-16f8e8342737

**Comment by Frudah** [comment]
This has been fixed with removing test code that was flooding the usart buffer.
