### ISSUE TITLE
Alpha 4g sign off

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#19]
### Version

alpha4g

### What is the issue?

About screen shows to be "Alpha 5". Looks like someone got ahead of themselves in the version control ;-)
![V4gAbout](https://github.com/user-attachments/assets/5219dbbc-e7b7-4882-b0e0-4f04953a3661)

Save settings screen has a language query. At lest the black screen of death is not shown as previous version.
https://github.com/user-attachments/assets/115739a1-19fd-4d91-945a-e3fb0ffbf0eb

**Comment by Miq1** [comment]
4g is the past 😉

**Comment by Smelter** [comment]
It may be the past, but it was the best version for removing the LEDs
flickering. I might just be going back to it!
