### ISSUE TITLE
One key press, two notes sound

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#22]
### Version

alpha5.1

### What is the issue?

Appears to be some form of "switch bounce" generated in the firmware.
https://github.com/user-attachments/assets/9d682cbc-9c11-49e7-a965-63463a2d1270

**Comment by Miq1** [comment]
No bug, but a feature. Fred described it when publishing alpha5. You can switch it off in the Settings.

**Comment by Smelter** [comment]
I have tried changing the sensitivity settings with inconsistent results.
The higher the numerical range the longer the gap between the initial note and the bounce note.

**Comment by Smelter** [comment]
Clock set to 'E' & 'IO' clears the problem. So the setting of 'IS' is the problem!

**Comment by Smelter** [comment]
Hokey Cokey?

**Comment by Frudah** [comment]
Is this with a daw or midi instrument? Which kind please. I made the Internal Only clock because I found sending the clock to my Moog was producing issues. I may have actually been wrong, as I also found an issue with the chord note sequencers to the Moog or DAW without it.

**Comment by Smelter** [comment]
> Is this with a daw or midi instrument? Which kind please. I made the Internal Only clock because I found sending the clock to my Moog was producing issues. I may have actually been wrong, as I also found an issue with the chord note sequencers to the Moog or DAW without it.

Observation is for MIDI over DIN via synth. This is my preference as I have a project waiting for key colours being declared in a SYSEX message, to have physical LEDs over the synth's keys.

**Comment by Frudah** [comment]
I know you sent me a few videos. Any way you can send me the sysex messages you want? if not, can you send the video links again?

**Comment by Frudah** [comment]
should be fixed for 5.2. reopen if you still have issues.
