### ISSUE TITLE
Chord naming not matching

### ISSUE THREAD

**Issue by Miq1** [Miq1/FredBoard#26]
### Version

alpha5.1.A

### What is the issue?

Scales mode, C Ionian, Live Notes ON.

Key L2-1 (left keyboard, row 2, column1) is displayed "GMaj+3" (G3, B3, D4).
Key L2-2 (right of the first) is displayed "GMaj+3" as well and has the same notes (well...).
Key L2-5 (fifth in that row) is also displayed as "GMaj+3", but has G3, B3, D4 and Gb4. Of course the additional note is lit up in the middle (third "V" key). But only switching that off and on again will change the chord name to "GMaj7+3".

**Comment by Frudah** [comment]
I think I know exactly where that’s at. Added the 7th on in code, but must’ve done it after it checks the definition.

**Comment by Frudah** [comment]
Fixed :)
