### ISSUE TITLE
Key 1 in key blocks 5+6 triggered by other keys of those blocks

### ISSUE THREAD

**Issue by Miq1** [Miq1/FredBoard#27]
### Version

alpha5.1.A

### What is the issue?

Scales mode. The top left key in the 4x4 grid blocks #5 and #6 is lit white and stays on, if any other key in that grid block is pressed. Pressing the top left key itself will clear the white, as will any chord key on the left keyboard.

The other notes in the 4x4 block have no white indication when pressed.

**Comment by Frudah** [comment]
should be fixed with 5.2. Code overhaul missed/lost some tracking variables, but they are back. Reopen if you find this is not the case.
