### ISSUE TITLE
Top line text overlap

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#29]
### Version

alpha5.3

### What is the issue?

Mode line text string length needs checking for overlap with blinking filled circle.
![IMG_20241111_174727071_HDR](https://github.com/user-attachments/assets/494d8598-eb4a-4129-9a8d-19ad544f8858)

**Comment by Frudah** [comment]
Condensed key and scale name. Longer names may still be cut off, but priority will be given to bpm display.
