### ISSUE TITLE
Wot no noise floor

### ISSUE THREAD

**Issue by Smelter** [Miq1/FredBoard#31]
### Version

alpha5.4

### What is the issue?

Menu listing shows no value for Noise Floor setting.
Looks like it defaults to 45 but nothing appears as confirmation.
![NoiseFloorNoDigits](https://github.com/user-attachments/assets/9d5c0778-7e09-4a35-bfca-a8122488bb06)

**Comment by Frudah** [comment]
it has been added as a submenu. arrow has been added for clarity.
