### ISSUE TITLE
Hanging notes

### ISSUE THREAD

**Issue by Miq1** [Miq1/FredBoard#6]
### Version

alpha4d (for alpha4f still valid)

### What is the issue?

When simultaneously pressing the outer 4 corner keys (to release all keys - MIDI panic) notes are triggered and left ON.

Some are releasable by pressing the same note again, others aren't.

**Comment by Frudah** [comment]
Note tracking system improved. MIDI panic function improved. New method is the two octave buttons. Note tracking buffers are now being cleared instead of just sending note off messages on all channels.
