### ISSUE TITLE
Switching between easy and standard chord modes requires three button presses

### ISSUE THREAD

**Issue by Miq1** [Miq1/FredBoard#8]
### Version

alpha4d

### What is the issue?

When in Scales mode, pressing the middle round button is supposed to toggle between easy and standard chords. It does, but only if pressed twice. Standard to easy chords needs just one press.

**Comment by Frudah** [comment]
This is a feature. Previously, the first two modes were duplicated, both being chromatic chords. Now, it’s 6 chord layout, diatonic chords and chromatic chords. Two layouts will look identical, Burt the chords loaded are not. I will need to add layout names to differentiate layouts that look identical.

**Comment by Frudah** [comment]
… and closing
